# site name
prefixName: Attack204
siteName: 
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.png
url: http://blog.attack204.com
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/attack204/cdn@1.1
pjax: 1
mathjax: 1

notice: attack又双叒叕换博客啦
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake }
  
  # 归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
  #   技术: {path: /categories/技术/, fa: fa-code }, 
  #   生活: {path: /categories/生活/, fa: fa-file-text-o }, 
  #   资源: {path: /categories/资源/, fa: fa-cloud-download }, 
  #   随想: {path: /categories/随想/, fa: fa-commenting-o },
  #   转载: {path: /categories/转载/, fa: fa-book }
  # } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    # 书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    影评: {path: /bangumi/, fa: fa-film faa-vertical }, 
    # 歌单: {path: /music/, fa: fa-headphones },
    # 图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  #赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于我: {path: /about/, fa: fa-leaf faa-wrench }
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  #   我？: {path: /about/, fa: fa-meetup}, 
  #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #   Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10

	# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

	# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot


# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /images/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/321916130, title: Bilibili, desc: 博主的b站视频, img: /images/startdash/bilibili.jpg}
  - {url: http://zwfymqz.cnblogs.com/, title: attack204的博客园, desc: 曾经的我, img: /images/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 02/19/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/attack204, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=364977201, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/attack-61/activities, img: /img/social/zhihu.png}
  email: {url: mailto:757394026@qq.com, img:  /img/social/email.svg}
  # wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/attack204, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=757394026&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://blog.attack204.com
  alipay: http://cdn.attack204.com/myqq.jpg
  wechat: http://cdn.attack204.com/myqq.jpg
  wechatSQ: http://cdn.attack204.com/myqq.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

# 关闭aplayer优化加载速度
# aplayer: 
#   id: 652849532
#   server: netease
#   type: playlist
#   fixed: true
#   autoplay: false
#   loop: all
#   order: random
#   preload: auto
#   volume: 0.7
#   mutex: true

# Valine
valine: true
v_appId: koz7QJsC5UmO6cQSQJbbynX1-gzGzoHsz
v_appKey: pwpT2rxLPwDQYCxi9rjeovTS
